### ISSUE TITLE
swap issues very soon

### ISSUE THREAD

**Issue by dereuromark** [alt3/cakebox-console#126] opened 2018-02-07 22:38 UTC
we should find better/saner defaults for current usage and use cases.
With medium apps you get this very soon from the start:

> The following exception is caused by a lack of memory or swap, or not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details
  [ErrorException]
  proc_open(): fork failed - Cannot allocate memory

As per https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors
This could be happening because the VPS runs out of memory and has no Swap space enabled.

running 'top' in parallel tells me, though:
```
KiB Mem :  1745168 total,  1271028 free,   347604 used,   126536 buff/cache
KiB Swap:   786428 total,   482516 free,   303912 used.  1254120 avail Mem
```

Seems like there is still enough free, so whats going on if it isnt the memory running out?

**Comment by bravo-kernel** [comment] 2018-02-09 07:59
Cakebox uses the ubuntu box defaults which are already optimized. I guess this should no longer happen when creating a new box with the PHP 7.x fix.

**Comment by bravo-kernel** [comment] 2018-03-03 13:57
Closing as I cannot reproduce this error on a fresh box (running for +1 months now)

**Closed as completed by bravo-kernel** 2018-03-03 13:57 UTC
